# NOTE : THIS ARE THE DEMO API KEYS SO NO NEEDED OF ANY ISSUES.BUT DO NOT ADD THE API KEYS IN THE GITHUB OR ENV FILES WHILE PRODUCTION 
# YOU CAN USE THIS KEYS FOR NOW NO ISSUES
API_KEY    = "aDboTQD17xmW9EvOdTkTHaXlEm36e7Eq26JBue8UNimC4BZ0MNJB2drNpTYYtdO1"
API_SECRET = "9LsORQcbFVaqI21dwPtN68dLUyyIOBDqNrHkZrcywrJZwSmUoMgOuU4vmTop9Dge"
